stages:
  - "build:images"
  - "push:images"

default:
  image: "docker.io/docker:stable"

build:images:
  stage: "build:images"
  before_script:
    - "apk add --no-cache coreutils git make xz"
  script:
    - "make IMAGE_BUILD_OPTS='--pull --no-cache' build-image"
    - "make save-image save-standalone"
  artifacts:
    expire_in: "15 mins"
    paths:
      - "./dist/*.tgz"

push:images:
  stage: "push:images"
  dependencies:
    - "build:images"
  only:
    - "/^biserver-[0-9]+\\.[0-9]+$/"
  before_script:
    - "apk add --no-cache coreutils git make xz"
    - "docker login -u \"${CI_REGISTRY_USER:?}\" -p \"${CI_REGISTRY_PASSWORD:?}\" \"${CI_REGISTRY:?}\""
  script:
    - "make load-image push-image"

push:standalone:
  stage: "push:images"
  dependencies:
    - "build:images"
  only:
    - "/^biserver-[0-9]+\\.[0-9]+$/"
  before_script:
    - "apk add --no-cache coreutils git make xz curl"
  script:
    - "curl -u \"${HTTP_UPLOAD_USER:?}:${HTTP_UPLOAD_PASS:?}\" -T ./dist/*_standalone.tgz \"${HTTP_UPLOAD_URL:?}\""
