stages:
  - "build:images"
  - "push:images"

default:
  image: "docker.io/docker:stable"

build:images:
  stage: "build:images"
  before_script:
    - "apk add --no-cache coreutils git make zstd"
  script:
    - "make IMAGE_BUILD_OPTS='--pull' build-image"
    - "make save-image save-standalone"
  artifacts:
    expire_in: "15 mins"
    paths:
      - "./dist/"

push:images:
  stage: "push:images"
  dependencies:
    - "build:images"
  only:
    - "/^biserver-[0-9]+\\.[0-9]+$/"
  before_script:
    - "apk add --no-cache coreutils git make zstd"
    - "docker login -u \"${REPO_DOCKER_RW_USER:?}\" -p \"${REPO_DOCKER_RW_PASSWORD:?}\" \"${REPO_DOCKER_REGISTRY:?}\""
  script:
    - "make load-image push-image"

push:standalone:
  stage: "push:images"
  dependencies:
    - "build:images"
  only:
    - "/^biserver-[0-9]+\\.[0-9]+$/"
  before_script:
    - "apk add --no-cache coreutils git make zstd curl"
  script:
    - "curl -u \"${REPO_RAW_LINCEBI_RW_USER:?}:${REPO_RAW_LINCEBI_RW_PASSWORD:?}\" -T ./dist/*_standalone.zip \"${REPO_RAW_LINCEBI_URL:?}\""
