image: docker:stable

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - nix*
  before_script:
    - docker info
    - apk add --no-cache coreutils make
  script:
    - make all
  artifacts:
    expire_in: 15 mins
    paths:
      - dist/

deploy:
  stage: deploy
  tags:
    - nix*
  dependencies:
    - build
  before_script:
    - apk add --no-cache coreutils curl
  script:
    - find ./dist/ -name 'pentaho-biserver_*.tgz' -exec curl -u "${DEPLOY_USER}:${DEPLOY_PASS}" -T '{}' "${DEPLOY_URL}" ';'
  only:
    - /^pentaho-biserver-[0-9]+\.[0-9]+$/
