image: "docker.io/docker:stable"

stages:
  - "build:images"
  - "push:images"

build:image:
  stage: "build:images"
  before_script:
    - "docker info"
    - "apk add --no-cache coreutils make"
  script:
    - "make save-image save-standalone"
  artifacts:
    expire_in: "15 mins"
    paths:
      - "dist/*.tgz"

push:image:
  stage: "push:images"
  before_script:
    - "apk add --no-cache coreutils make"
    - "docker login -u \"${CI_REGISTRY_USER:?}\" -p \"${CI_REGISTRY_PASSWORD:?}\" \"${CI_REGISTRY:?}\" >/dev/null 2>&1"
  script:
    - "make load-image push-image"
  only:
    - "/^biserver-[0-9]+\.[0-9]+$/"
  dependencies:
    - "build:image"

push:standalone:
  stage: "push:images"
  before_script:
    - "apk add --no-cache coreutils curl"
  script:
    - "curl -u \"${HTTP_UPLOAD_USER:?}:${HTTP_UPLOAD_PASS:?}\" -T ./dist/*_standalone.tgz \"${HTTP_UPLOAD_URL:?}\""
  only:
    - "/^biserver-[0-9]+\.[0-9]+$/"
  dependencies:
    - "build:image"
