version: "3.7"

services:

  caddy:
    image: "docker.io/caddy:2"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "caddy-data:/data/"
    environment:
      TLS_DOMAIN: "${TLS_DOMAIN}"
      TLS_ACCOUNT: "${TLS_ACCOUNT}"
      TLS_CA: "${TLS_CA}"

  biserver-1:
    image: "repo.stratebi.com/lincebi/biserver:9.0.0.0-423"
    restart: "on-failure:3"
    networks:
      - "biserver"
    volumes:
      - "./biserver.init.d/:/etc/biserver.init.d/:ro"
    environment:
      IS_PROXIED: "true"
      PROXY_SCHEME: "https"
      PROXY_PORT: "443"
      FQSU_PROTOCOL: "https"
      FQSU_DOMAIN: "${TLS_DOMAIN}"
      FQSU_PORT: "443"
      DEFAULT_ADMIN_PASSWORD: "${DEFAULT_ADMIN_PASSWORD}"
      STORAGE_TYPE: "mysql"
      MYSQL_HOST: "mariadb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_JDBC_PROPS: "useSSL=false"
      MYSQL_JACKRABBIT_USER: "${DB_JACKRABBIT_USER}"
      MYSQL_JACKRABBIT_PASSWORD: "${DB_JACKRABBIT_PASSWORD}"
      MYSQL_JACKRABBIT_DATABASE: "${DB_JACKRABBIT_DATABASE}"
      MYSQL_HIBERNATE_USER: "${DB_HIBERNATE_USER}"
      MYSQL_HIBERNATE_PASSWORD: "${DB_HIBERNATE_PASSWORD}"
      MYSQL_HIBERNATE_DATABASE: "${DB_HIBERNATE_DATABASE}"
      MYSQL_QUARTZ_USER: "${DB_QUARTZ_USER}"
      MYSQL_QUARTZ_PASSWORD: "${DB_QUARTZ_PASSWORD}"
      MYSQL_QUARTZ_DATABASE: "${DB_QUARTZ_DATABASE}"
    depends_on:
      - "mariadb"

  biserver-2:
    image: "repo.stratebi.com/lincebi/biserver:9.0.0.0-423"
    restart: "on-failure:3"
    networks:
      - "biserver"
    volumes:
      - "./biserver.init.d/:/etc/biserver.init.d/:ro"
    environment:
      IS_PROXIED: "true"
      PROXY_SCHEME: "https"
      PROXY_PORT: "443"
      FQSU_PROTOCOL: "https"
      FQSU_DOMAIN: "${TLS_DOMAIN}"
      FQSU_PORT: "443"
      DEFAULT_ADMIN_PASSWORD: "${DEFAULT_ADMIN_PASSWORD}"
      STORAGE_TYPE: "mysql"
      MYSQL_HOST: "mariadb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_JDBC_PROPS: "useSSL=false"
      MYSQL_JACKRABBIT_USER: "${DB_JACKRABBIT_USER}"
      MYSQL_JACKRABBIT_PASSWORD: "${DB_JACKRABBIT_PASSWORD}"
      MYSQL_JACKRABBIT_DATABASE: "${DB_JACKRABBIT_DATABASE}"
      MYSQL_HIBERNATE_USER: "${DB_HIBERNATE_USER}"
      MYSQL_HIBERNATE_PASSWORD: "${DB_HIBERNATE_PASSWORD}"
      MYSQL_HIBERNATE_DATABASE: "${DB_HIBERNATE_DATABASE}"
      MYSQL_QUARTZ_USER: "${DB_QUARTZ_USER}"
      MYSQL_QUARTZ_PASSWORD: "${DB_QUARTZ_PASSWORD}"
      MYSQL_QUARTZ_DATABASE: "${DB_QUARTZ_DATABASE}"
    entrypoint: "/bin/sh"
    command: |
      -euc "
        until [ \"$$(curl -so /dev/null -w '%{http_code}' -Im 5 'http://biserver-1:8080/pentaho/')\" = '302' ]; do sleep 10; done
        exec /usr/bin/tini /usr/share/biserver/bin/init.sh
      "
    depends_on:
      - "mariadb"

  mariadb:
    image: "docker.io/mariadb:10.5"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "127.0.0.1:3306:3306/tcp"
    volumes:
      - "mariadb-data:/var/lib/mysql/"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

networks:

  biserver:
    driver: "bridge"
    internal: false

volumes:

  caddy-data:
  mariadb-data:
