version: "3.7"

services:

  caddy:
    image: "docker.io/hectormolinero/caddy:latest"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      ROOT_REDIRECT: "${ROOT_REDIRECT}"
      TLS: "${TLS}"
      TLS_CASERVER: "${TLS_CASERVER}"
      TLS_DOMAIN: "${TLS_DOMAIN}"
      TLS_EMAIL: "${TLS_EMAIL}"
      TLS_DNSPROVIDER: "${TLS_DNSPROVIDER}"
      CLOUDFLARE_EMAIL: "${CLOUDFLARE_EMAIL}"
      CLOUDFLARE_API_KEY: "${CLOUDFLARE_API_KEY}"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "caddy-data:/var/lib/caddy/"

  postgres:
    image: "docker.io/postgres:12"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "127.0.0.1:5432:5432/tcp"
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

  biserver-helium:
    image: "repo.stratebi.com/lincebi/biserver:9.0.0.0-423"
    restart: "on-failure:3"
    networks:
      - "biserver"
    volumes:
      - "./biserver.init.d/:/etc/biserver.init.d/:ro"
    environment:
      IS_PROXIED: "true"
      PROXY_SCHEME: "https"
      PROXY_PORT: "443"
      FQSU_PROTOCOL: "https"
      FQSU_DOMAIN: "${TLS_DOMAIN}"
      FQSU_PORT: "443"
      WEBAPP_PENTAHO_DIRNAME: "helium"
      WEBAPP_PENTAHO_STYLE_DIRNAME: "helium-style"
      STORAGE_TYPE: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_JACKRABBIT_USER: "${DB_HELIUM_JACKRABBIT_USER}"
      POSTGRES_JACKRABBIT_PASSWORD: "${DB_HELIUM_JACKRABBIT_PASSWORD}"
      POSTGRES_JACKRABBIT_DATABASE: "${DB_HELIUM_JACKRABBIT_DATABASE}"
      POSTGRES_HIBERNATE_USER: "${DB_HELIUM_HIBERNATE_USER}"
      POSTGRES_HIBERNATE_PASSWORD: "${DB_HELIUM_HIBERNATE_PASSWORD}"
      POSTGRES_HIBERNATE_DATABASE: "${DB_HELIUM_HIBERNATE_DATABASE}"
      POSTGRES_QUARTZ_USER: "${DB_HELIUM_QUARTZ_USER}"
      POSTGRES_QUARTZ_PASSWORD: "${DB_HELIUM_QUARTZ_PASSWORD}"
      POSTGRES_QUARTZ_DATABASE: "${DB_HELIUM_QUARTZ_DATABASE}"
    depends_on:
      - "postgres"

  biserver-argon:
    image: "repo.stratebi.com/lincebi/biserver:9.0.0.0-423"
    restart: "on-failure:3"
    networks:
      - "biserver"
    volumes:
      - "./biserver.init.d/:/etc/biserver.init.d/:ro"
    environment:
      IS_PROXIED: "true"
      PROXY_SCHEME: "https"
      PROXY_PORT: "443"
      FQSU_PROTOCOL: "https"
      FQSU_DOMAIN: "${TLS_DOMAIN}"
      FQSU_PORT: "443"
      WEBAPP_PENTAHO_DIRNAME: "argon"
      WEBAPP_PENTAHO_STYLE_DIRNAME: "argon-style"
      STORAGE_TYPE: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_JACKRABBIT_USER: "${DB_ARGON_JACKRABBIT_USER}"
      POSTGRES_JACKRABBIT_PASSWORD: "${DB_ARGON_JACKRABBIT_PASSWORD}"
      POSTGRES_JACKRABBIT_DATABASE: "${DB_ARGON_JACKRABBIT_DATABASE}"
      POSTGRES_HIBERNATE_USER: "${DB_ARGON_HIBERNATE_USER}"
      POSTGRES_HIBERNATE_PASSWORD: "${DB_ARGON_HIBERNATE_PASSWORD}"
      POSTGRES_HIBERNATE_DATABASE: "${DB_ARGON_HIBERNATE_DATABASE}"
      POSTGRES_QUARTZ_USER: "${DB_ARGON_QUARTZ_USER}"
      POSTGRES_QUARTZ_PASSWORD: "${DB_ARGON_QUARTZ_PASSWORD}"
      POSTGRES_QUARTZ_DATABASE: "${DB_ARGON_QUARTZ_DATABASE}"
    depends_on:
      - "postgres"

networks:

  biserver:
    driver: "bridge"
    internal: false

volumes:

  caddy-data:
  postgres-data:
