version: "3.9"

services:

  caddy:
    image: "docker.io/caddy:2"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "caddy-data:/data/"
    environment:
      TLS_DOMAIN: "${TLS_DOMAIN}"
      TLS_ISSUER: "${TLS_ISSUER}"
      TLS_ISSUER_CA: "${TLS_ISSUER_CA}"
      TLS_ISSUER_EMAIL: "${TLS_ISSUER_EMAIL}"

  biserver:
    image: "repo.stratebi.com/lincebi/biserver:9.1.0.0-324"
    restart: "on-failure:3"
    networks:
      - "biserver"
    volumes:
      - "./biserver.init.d/:/etc/biserver.init.d/:ro"
    environment:
      IS_PROXIED: "true"
      PROXY_SCHEME: "https"
      PROXY_PORT: "443"
      FQSU_PROTOCOL: "https"
      FQSU_DOMAIN: "${TLS_DOMAIN}"
      FQSU_PORT: "443"
      DEFAULT_ADMIN_PASSWORD: "${DEFAULT_ADMIN_PASSWORD}"
      STORAGE_TYPE: "tidb"
      TIDB_HOST: "tidb-1"
      TIDB_USER: "root"
      TIDB_PASSWORD: "${DB_PASSWORD}"
      TIDB_JDBC_URL: "jdbc:mysql:loadbalance://tidb-1:4000,tidb-2:4000,tidb-3:4000"
      TIDB_JDBC_PROPS: "useSSL=false"
      TIDB_JACKRABBIT_USER: "${DB_JACKRABBIT_USER}"
      TIDB_JACKRABBIT_PASSWORD: "${DB_JACKRABBIT_PASSWORD}"
      TIDB_JACKRABBIT_DATABASE: "${DB_JACKRABBIT_DATABASE}"
      TIDB_HIBERNATE_USER: "${DB_HIBERNATE_USER}"
      TIDB_HIBERNATE_PASSWORD: "${DB_HIBERNATE_PASSWORD}"
      TIDB_HIBERNATE_DATABASE: "${DB_HIBERNATE_DATABASE}"
      TIDB_QUARTZ_USER: "${DB_QUARTZ_USER}"
      TIDB_QUARTZ_PASSWORD: "${DB_QUARTZ_PASSWORD}"
      TIDB_QUARTZ_DATABASE: "${DB_QUARTZ_DATABASE}"

  tidb-1:
    image: "docker.io/pingcap/tidb:latest"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "127.0.0.1:4000:4000/tcp"
    volumes:
      - "tidb-logs:/logs/"
    command:
      - "--host=0.0.0.0"
      - "--advertise-address=tidb-1"
      - "--path=pd-0:2379,pd-1:2379,pd-2:2379"
      - "--store=tikv"
      - "--log-file=/logs/tidb-1.log"
    depends_on:
      - "tikv-0"
      - "tikv-1"
      - "tikv-2"

  tidb-2:
    image: "docker.io/pingcap/tidb:latest"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "127.0.0.1:4001:4000/tcp"
    volumes:
      - "tidb-logs:/logs/"
    command:
      - "--host=0.0.0.0"
      - "--advertise-address=tidb-2"
      - "--path=pd-0:2379,pd-1:2379,pd-2:2379"
      - "--store=tikv"
      - "--log-file=/logs/tidb-2.log"
    depends_on:
      - "tikv-0"
      - "tikv-1"
      - "tikv-2"

  tidb-3:
    image: "docker.io/pingcap/tidb:latest"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "127.0.0.1:4002:4000/tcp"
    volumes:
      - "tidb-logs:/logs/"
    command:
      - "--host=0.0.0.0"
      - "--advertise-address=tidb-3"
      - "--path=pd-0:2379,pd-1:2379,pd-2:2379"
      - "--store=tikv"
      - "--log-file=/logs/tidb-3.log"
    depends_on:
      - "tikv-0"
      - "tikv-1"
      - "tikv-2"

  tikv-0:
    image: "docker.io/pingcap/tikv:latest"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "127.0.0.1:20160:20160/tcp"
    volumes:
      - "tidb-data:/data/"
      - "tidb-logs:/logs/"
    command:
      - "--addr=0.0.0.0:20160"
      - "--advertise-addr=tikv-0:20160"
      - "--pd=pd-0:2379,pd-1:2379,pd-2:2379"
      - "--data-dir=/data/tikv-0/"
      - "--log-file=/logs/tikv-0.log"
    depends_on:
      - "pd-0"
      - "pd-1"
      - "pd-2"

  tikv-1:
    image: "docker.io/pingcap/tikv:latest"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "127.0.0.1:20161:20160/tcp"
    volumes:
      - "tidb-data:/data/"
      - "tidb-logs:/logs/"
    command:
      - "--addr=0.0.0.0:20160"
      - "--advertise-addr=tikv-1:20160"
      - "--pd=pd-0:2379,pd-1:2379,pd-2:2379"
      - "--data-dir=/data/tikv-1/"
      - "--log-file=/logs/tikv-1.log"
    depends_on:
      - "pd-0"
      - "pd-1"
      - "pd-2"

  tikv-2:
    image: "docker.io/pingcap/tikv:latest"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "127.0.0.1:20162:20160/tcp"
    volumes:
      - "tidb-data:/data/"
      - "tidb-logs:/logs/"
    command:
      - "--addr=0.0.0.0:20160"
      - "--advertise-addr=tikv-2:20160"
      - "--pd=pd-0:2379,pd-1:2379,pd-2:2379"
      - "--data-dir=/data/tikv-2/"
      - "--log-file=/logs/tikv-2.log"
    depends_on:
      - "pd-0"
      - "pd-1"
      - "pd-2"

  pd-0:
    image: "docker.io/pingcap/pd:latest"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "127.0.0.1:2379:2379/tcp"
    volumes:
      - "tidb-data:/data/"
      - "tidb-logs:/logs/"
    command:
      - "--name=pd-0"
      - "--client-urls=http://0.0.0.0:2379"
      - "--peer-urls=http://0.0.0.0:2380"
      - "--advertise-client-urls=http://pd-0:2379"
      - "--advertise-peer-urls=http://pd-0:2380"
      - "--initial-cluster=pd-0=http://pd-0:2380,pd-1=http://pd-1:2380,pd-2=http://pd-2:2380"
      - "--data-dir=/data/pd-0/"
      - "--log-file=/logs/pd-0.log"

  pd-1:
    image: "docker.io/pingcap/pd:latest"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "127.0.0.1:2380:2379/tcp"
    volumes:
      - "tidb-data:/data/"
      - "tidb-logs:/logs/"
    command:
      - "--name=pd-1"
      - "--client-urls=http://0.0.0.0:2379"
      - "--peer-urls=http://0.0.0.0:2380"
      - "--advertise-client-urls=http://pd-1:2379"
      - "--advertise-peer-urls=http://pd-1:2380"
      - "--initial-cluster=pd-0=http://pd-0:2380,pd-1=http://pd-1:2380,pd-2=http://pd-2:2380"
      - "--data-dir=/data/pd-1/"
      - "--log-file=/logs/pd-1.log"

  pd-2:
    image: "docker.io/pingcap/pd:latest"
    restart: "on-failure:3"
    networks:
      - "biserver"
    ports:
      - "127.0.0.1:2381:2379/tcp"
    volumes:
      - "tidb-data:/data/"
      - "tidb-logs:/logs/"
    command:
      - "--name=pd-2"
      - "--client-urls=http://0.0.0.0:2379"
      - "--peer-urls=http://0.0.0.0:2380"
      - "--advertise-client-urls=http://pd-2:2379"
      - "--advertise-peer-urls=http://pd-2:2380"
      - "--initial-cluster=pd-0=http://pd-0:2380,pd-1=http://pd-1:2380,pd-2=http://pd-2:2380"
      - "--data-dir=/data/pd-2/"
      - "--log-file=/logs/pd-2.log"

networks:

  biserver:
    driver: "bridge"
    internal: false

volumes:

  caddy-data:
  tidb-data:
  tidb-logs:
