# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: "biserver"

# https://hub.docker.com/_/caddy
x-caddy-image: &caddy-image "docker.io/caddy:2"
# https://repo.stratebi.com
x-biserver-image: &biserver-image "repo.stratebi.com/lincebi/biserver:9.5.2.0-272-2"
# https://hub.docker.com/_/postgres
x-postgres-image: &postgres-image "docker.io/postgres:16-bookworm"

services:

  caddy:
    image: *caddy-image
    restart: "on-failure:3"
    container_name: "biserver-caddy"
    hostname: "caddy"
    networks:
      - "biserver"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - { type: "bind", source: "./config/caddy/", target: "/etc/caddy/", read_only: true }
      - { type: "volume", source: "caddy-data", target: "/data/" }
      - { type: "volume", source: "biserver-helium-logs", target: "/var/www/html/logs/helium/", read_only: true }
      - { type: "volume", source: "biserver-argon-logs", target: "/var/www/html/logs/argon/", read_only: true }
    environment:
      DOMAIN: "${DOMAIN:?}"
      TLS_ISSUER: "${TLS_ISSUER:?}"
      TLS_ISSUER_CA: "${TLS_ISSUER_CA:?}"
      TLS_ISSUER_EMAIL: "${TLS_ISSUER_EMAIL:?}"
      TLS_KEY: "${TLS_KEY:-}"
      TLS_CERT: "${TLS_CERT:-}"
      BASIC_AUTH_PASSWORD: "${DEFAULT_ADMIN_PASSWORD:?}"
    entrypoint: "/bin/sh"
    command:
      - "-euc"
      - |
        export BASIC_AUTH_PASSWORD_HASH=$(printenv BASIC_AUTH_PASSWORD | caddy hash-password)
        exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile

  biserver-helium:
    image: *biserver-image
    restart: "on-failure:3"
    container_name: "biserver-helium"
    hostname: "biserver-helium"
    networks:
      - "biserver"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - { type: "bind", source: "./config/biserver/biserver.init.d/", target: "/etc/biserver.init.d/", read_only: true }
      - { type: "volume", source: "biserver-helium-logs", target: "/var/lib/biserver/tomcat/logs/" }
    environment:
      IS_PROXIED: "true"
      PROXY_SCHEME: "https"
      PROXY_PORT: "443"
      FQSU_PROTOCOL: "https"
      FQSU_DOMAIN: "${DOMAIN:?}"
      FQSU_PORT: "443"
      LOAD_SAMPLES: "${LOAD_SAMPLES:-true}"
      WEBAPP_PENTAHO_DIRNAME: "helium"
      WEBAPP_PENTAHO_STYLE_DIRNAME: "helium-style"
      DEFAULT_ADMIN_PASSWORD: "${DEFAULT_ADMIN_PASSWORD:?}"
      STORAGE_TYPE: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${DB_PASSWORD:?}"
      POSTGRES_JACKRABBIT_USER: "${DB_HELIUM_JACKRABBIT_USER:-helium_jackrabbit}"
      POSTGRES_JACKRABBIT_PASSWORD: "${DB_HELIUM_JACKRABBIT_PASSWORD:?}"
      POSTGRES_JACKRABBIT_DATABASE: "${DB_HELIUM_JACKRABBIT_DATABASE:-helium_jackrabbit}"
      POSTGRES_HIBERNATE_USER: "${DB_HELIUM_HIBERNATE_USER:-helium_hibernate}"
      POSTGRES_HIBERNATE_PASSWORD: "${DB_HELIUM_HIBERNATE_PASSWORD:?}"
      POSTGRES_HIBERNATE_DATABASE: "${DB_HELIUM_HIBERNATE_DATABASE:-helium_hibernate}"
      POSTGRES_QUARTZ_USER: "${DB_HELIUM_QUARTZ_USER:-helium_quartz}"
      POSTGRES_QUARTZ_PASSWORD: "${DB_HELIUM_QUARTZ_PASSWORD:?}"
      POSTGRES_QUARTZ_DATABASE: "${DB_HELIUM_QUARTZ_DATABASE:-helium_quartz}"
    depends_on:
      postgres:
        condition: "service_healthy"

  biserver-argon:
    image: *biserver-image
    restart: "on-failure:3"
    container_name: "biserver-argon"
    hostname: "biserver-argon"
    networks:
      - "biserver"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - { type: "bind", source: "./config/biserver/biserver.init.d/", target: "/etc/biserver.init.d/", read_only: true }
      - { type: "volume", source: "biserver-argon-logs", target: "/var/lib/biserver/tomcat/logs/" }
    environment:
      IS_PROXIED: "true"
      PROXY_SCHEME: "https"
      PROXY_PORT: "443"
      FQSU_PROTOCOL: "https"
      FQSU_DOMAIN: "${DOMAIN:?}"
      FQSU_PORT: "443"
      LOAD_SAMPLES: "${LOAD_SAMPLES:-true}"
      WEBAPP_PENTAHO_DIRNAME: "argon"
      WEBAPP_PENTAHO_STYLE_DIRNAME: "argon-style"
      DEFAULT_ADMIN_PASSWORD: "${DEFAULT_ADMIN_PASSWORD:?}"
      STORAGE_TYPE: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${DB_PASSWORD:?}"
      POSTGRES_JACKRABBIT_USER: "${DB_ARGON_JACKRABBIT_USER:-argon_jackrabbit}"
      POSTGRES_JACKRABBIT_PASSWORD: "${DB_ARGON_JACKRABBIT_PASSWORD:?}"
      POSTGRES_JACKRABBIT_DATABASE: "${DB_ARGON_JACKRABBIT_DATABASE:-argon_jackrabbit}"
      POSTGRES_HIBERNATE_USER: "${DB_ARGON_HIBERNATE_USER:-argon_hibernate}"
      POSTGRES_HIBERNATE_PASSWORD: "${DB_ARGON_HIBERNATE_PASSWORD:?}"
      POSTGRES_HIBERNATE_DATABASE: "${DB_ARGON_HIBERNATE_DATABASE:-argon_hibernate}"
      POSTGRES_QUARTZ_USER: "${DB_ARGON_QUARTZ_USER:-argon_quartz}"
      POSTGRES_QUARTZ_PASSWORD: "${DB_ARGON_QUARTZ_PASSWORD:?}"
      POSTGRES_QUARTZ_DATABASE: "${DB_ARGON_QUARTZ_DATABASE:-argon_quartz}"
    depends_on:
      postgres:
        condition: "service_healthy"

  postgres:
    image: *postgres-image
    restart: "on-failure:3"
    container_name: "biserver-postgres"
    hostname: "postgres"
    networks:
      - "biserver"
    ports:
      - "${POSTGRES_HOST:-127.0.0.1}:${POSTGRES_PORT:-5432}:5432/tcp"
    volumes:
      - { type: "bind", source: "./config/postgres/initdb.d/", target: "/docker-entrypoint-initdb.d/", read_only: true }
      - { type: "volume", source: "postgres-data", target: "/var/lib/postgresql/data/" }
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${DB_PASSWORD:?}"
    healthcheck:
      test: ["CMD", "pg_isready", "-qU", "postgres"]
      start_period: "60s"
      interval: "30s"
      timeout: "10s"
      retries: 2

networks:

  biserver:
    name: "biserver"
    internal: false

volumes:

  caddy-data:
    name: "biserver-caddy-data"

  biserver-helium-logs:
    name: "biserver-helium-logs"

  biserver-argon-logs:
    name: "biserver-argon-logs"

  postgres-data:
    name: "biserver-postgres-data"
