\set POSTGRES_KEYCLOAK_USER `printf -- '%s' "${POSTGRES_KEYCLOAK_USER}"`
\set POSTGRES_KEYCLOAK_PASSWORD `printf -- '%s' "${POSTGRES_KEYCLOAK_PASSWORD}"`
\set POSTGRES_KEYCLOAK_DATABASE `printf -- '%s' "${POSTGRES_KEYCLOAK_DATABASE}"`

CREATE USER :"POSTGRES_KEYCLOAK_USER" PASSWORD :'POSTGRES_KEYCLOAK_PASSWORD';
CREATE DATABASE :"POSTGRES_KEYCLOAK_DATABASE" WITH OWNER = :"POSTGRES_KEYCLOAK_USER" ENCODING = 'UTF8' TABLESPACE = pg_default;
GRANT ALL PRIVILEGES ON DATABASE :"POSTGRES_KEYCLOAK_DATABASE" TO :"POSTGRES_KEYCLOAK_USER";

\connect :"POSTGRES_KEYCLOAK_DATABASE" :"POSTGRES_KEYCLOAK_USER"
