#!/bin/sh

set -eu
export LC_ALL=C

. /usr/local/bin/setup-biserver-set-utils

########

[ -z "${FULLY_QUALIFIED_SERVER_URL:-}" ]         && export FULLY_QUALIFIED_SERVER_URL="http://localhost:8080/${BISERVER_WEBAPP_PENTAHO_DIRNAME}/"

if [ "${BISERVER_STORAGE}" = 'local' ]; then

	[ -z "${DBCON_HOST:-}" ]                     && export DBCON_HOST=
	[ -z "${DBCON_PORT:-}" ]                     && export DBCON_PORT=
	[ -z "${DBCON_USER:-}" ]                     && export DBCON_USER=
	[ -z "${DBCON_PASSWORD:-}" ]                 && export DBCON_PASSWORD='password'
	[ -z "${DBCON_DATABASE:-}" ]                 && export DBCON_DATABASE=

	[ -z "${DBCON_DATABASE_TYPE:-}" ]            && export DBCON_DATABASE_TYPE='hsqldb'
	[ -z "${DBCON_DRIVER_CLASS:-}" ]             && export DBCON_DRIVER_CLASS='org.hsqldb.jdbcDriver'
	[ -z "${DBCON_DIALECT_CLASS:-}" ]            && export DBCON_DIALECT_CLASS='org.hibernate.dialect.HSQLDialect'
	[ -z "${DBCON_FILESYSTEM_CLASS:-}" ]         && export DBCON_FILESYSTEM_CLASS='org.apache.jackrabbit.core.fs.local.LocalFileSystem'
	[ -z "${DBCON_DATASTORE_CLASS:-}" ]          && export DBCON_DATASTORE_CLASS='org.apache.jackrabbit.core.data.FileDataStore'
	[ -z "${DBCON_PERSISTENCEMANAGER_CLASS:-}" ] && export DBCON_PERSISTENCEMANAGER_CLASS='org.apache.jackrabbit.core.persistence.pool.H2PersistenceManager'
	[ -z "${DBCON_VALIDATIONQUERY:-}" ]          && export DBCON_VALIDATIONQUERY='select count(*) from INFORMATION_SCHEMA.SYSTEM_SEQUENCES'

	[ -z "${DBCON_JACKRABBIT_USER:-}" ]          && export DBCON_JACKRABBIT_USER='jcr_user'
	[ -z "${DBCON_JACKRABBIT_PASSWORD:-}" ]      && export DBCON_JACKRABBIT_PASSWORD="${DBCON_PASSWORD}"
	[ -z "${DBCON_JACKRABBIT_DATABASE:-}" ]      && export DBCON_JACKRABBIT_DATABASE='jackrabbit'
	[ -z "${DBCON_JACKRABBIT_URL:-}" ]           && export DBCON_JACKRABBIT_URL='jdbc:h2:${rep.home}/version/db'

	[ -z "${DBCON_HIBERNATE_USER:-}" ]           && export DBCON_HIBERNATE_USER='hibuser'
	[ -z "${DBCON_HIBERNATE_PASSWORD:-}" ]       && export DBCON_HIBERNATE_PASSWORD="${DBCON_PASSWORD}"
	[ -z "${DBCON_HIBERNATE_DATABASE:-}" ]       && export DBCON_HIBERNATE_DATABASE='hibernate'
	[ -z "${DBCON_HIBERNATE_URL:-}" ]            && export DBCON_HIBERNATE_URL="jdbc:hsqldb:hsql://localhost/${DBCON_HIBERNATE_DATABASE}"
	[ -z "${DBCON_HIBERNATE_CONFIG_FILE:-}" ]    && export DBCON_HIBERNATE_CONFIG_FILE='system/hibernate/hsql.hibernate.cfg.xml'

	[ -z "${DBCON_QUARTZ_USER:-}" ]              && export DBCON_QUARTZ_USER='pentaho_user'
	[ -z "${DBCON_QUARTZ_PASSWORD:-}" ]          && export DBCON_QUARTZ_PASSWORD="${DBCON_PASSWORD}"
	[ -z "${DBCON_QUARTZ_DATABASE:-}" ]          && export DBCON_QUARTZ_DATABASE='quartz'
	[ -z "${DBCON_QUARTZ_URL:-}" ]               && export DBCON_QUARTZ_URL="jdbc:hsqldb:hsql://localhost/${DBCON_QUARTZ_DATABASE}"

elif [ "${BISERVER_STORAGE}" = 'postgres' ]; then

	[ -z "${DBCON_HOST:-}" ]                     && export DBCON_HOST='localhost'
	[ -z "${DBCON_PORT:-}" ]                     && export DBCON_PORT='5432'
	[ -z "${DBCON_USER:-}" ]                     && export DBCON_USER='postgres'
	[ -z "${DBCON_PASSWORD:-}" ]                 && export DBCON_PASSWORD="${DBCON_USER}"
	[ -z "${DBCON_DATABASE:-}" ]                 && export DBCON_DATABASE="${DBCON_USER}"

	[ -z "${DBCON_DATABASE_TYPE:-}" ]            && export DBCON_DATABASE_TYPE='postgresql'
	[ -z "${DBCON_DRIVER_CLASS:-}" ]             && export DBCON_DRIVER_CLASS='org.postgresql.Driver'
	[ -z "${DBCON_DIALECT_CLASS:-}" ]            && export DBCON_DIALECT_CLASS='org.hibernate.dialect.PostgreSQLDialect'
	[ -z "${DBCON_FILESYSTEM_CLASS:-}" ]         && export DBCON_FILESYSTEM_CLASS='org.apache.jackrabbit.core.fs.db.DbFileSystem'
	[ -z "${DBCON_DATASTORE_CLASS:-}" ]          && export DBCON_DATASTORE_CLASS='org.apache.jackrabbit.core.data.db.DbDataStore'
	[ -z "${DBCON_PERSISTENCEMANAGER_CLASS:-}" ] && export DBCON_PERSISTENCEMANAGER_CLASS='org.apache.jackrabbit.core.persistence.bundle.PostgreSQLPersistenceManager'
	[ -z "${DBCON_VALIDATIONQUERY:-}" ]          && export DBCON_VALIDATIONQUERY='select 1'

	[ -z "${DBCON_JACKRABBIT_USER:-}" ]          && export DBCON_JACKRABBIT_USER='jcr_user'
	[ -z "${DBCON_JACKRABBIT_PASSWORD:-}" ]      && export DBCON_JACKRABBIT_PASSWORD="${DBCON_PASSWORD}"
	[ -z "${DBCON_JACKRABBIT_DATABASE:-}" ]      && export DBCON_JACKRABBIT_DATABASE='jackrabbit'
	[ -z "${DBCON_JACKRABBIT_URL:-}" ]           && export DBCON_JACKRABBIT_URL="jdbc:postgresql://${DBCON_HOST}:${DBCON_PORT}/${DBCON_JACKRABBIT_DATABASE}"

	[ -z "${DBCON_HIBERNATE_USER:-}" ]           && export DBCON_HIBERNATE_USER='hibuser'
	[ -z "${DBCON_HIBERNATE_PASSWORD:-}" ]       && export DBCON_HIBERNATE_PASSWORD="${DBCON_PASSWORD}"
	[ -z "${DBCON_HIBERNATE_DATABASE:-}" ]       && export DBCON_HIBERNATE_DATABASE='hibernate'
	[ -z "${DBCON_HIBERNATE_URL:-}" ]            && export DBCON_HIBERNATE_URL="jdbc:postgresql://${DBCON_HOST}:${DBCON_PORT}/${DBCON_HIBERNATE_DATABASE}"
	[ -z "${DBCON_HIBERNATE_CONFIG_FILE:-}" ]    && export DBCON_HIBERNATE_CONFIG_FILE='system/hibernate/postgresql.hibernate.cfg.xml'

	[ -z "${DBCON_QUARTZ_USER:-}" ]              && export DBCON_QUARTZ_USER='pentaho_user'
	[ -z "${DBCON_QUARTZ_PASSWORD:-}" ]          && export DBCON_QUARTZ_PASSWORD="${DBCON_PASSWORD}"
	[ -z "${DBCON_QUARTZ_DATABASE:-}" ]          && export DBCON_QUARTZ_DATABASE='quartz'
	[ -z "${DBCON_QUARTZ_URL:-}" ]               && export DBCON_QUARTZ_URL="jdbc:postgresql://${DBCON_HOST}:${DBCON_PORT}/${DBCON_QUARTZ_DATABASE}"

else
	logFail "Unknown storage type: ${BISERVER_STORAGE}"
	exit 1
fi

export CATALINA_HOME_SUBST="$(quoteSubst "${CATALINA_HOME}")"
export CATALINA_BASE_SUBST="$(quoteSubst "${CATALINA_BASE}")"

export BISERVER_HOME_SUBST="$(quoteSubst "${BISERVER_HOME}")"

export BISERVER_KETTLE_DIRNAME_SUBST="$(quoteSubst "${BISERVER_KETTLE_DIRNAME}")"
export BISERVER_SOLUTIONS_DIRNAME_SUBST="$(quoteSubst "${BISERVER_SOLUTIONS_DIRNAME}")"
export BISERVER_DATA_DIRNAME_SUBST="$(quoteSubst "${BISERVER_DATA_DIRNAME}")"

export BISERVER_WEBAPP_PENTAHO_DIRNAME_SUBST="$(quoteSubst "${BISERVER_WEBAPP_PENTAHO_DIRNAME}")"
export BISERVER_WEBAPP_PENTAHO_STYLE_DIRNAME_SUBST="$(quoteSubst "${BISERVER_WEBAPP_PENTAHO_STYLE_DIRNAME}")"

export FULLY_QUALIFIED_SERVER_URL_SUBST="$(quoteSubst "${FULLY_QUALIFIED_SERVER_URL}")"

export DBCON_HOST_SUBST="$(quoteSubst "${DBCON_HOST}")"
export DBCON_PORT_SUBST="$(quoteSubst "${DBCON_PORT}")"
export DBCON_USER_SUBST="$(quoteSubst "${DBCON_USER}")"
export DBCON_PASSWORD_SUBST="$(quoteSubst "${DBCON_PASSWORD}")"
export DBCON_DATABASE_SUBST="$(quoteSubst "${DBCON_DATABASE}")"

export DBCON_DATABASE_TYPE_SUBST="$(quoteSubst "${DBCON_DATABASE_TYPE}")"
export DBCON_DRIVER_CLASS_SUBST="$(quoteSubst "${DBCON_DRIVER_CLASS}")"
export DBCON_DIALECT_CLASS_SUBST="$(quoteSubst "${DBCON_DIALECT_CLASS}")"
export DBCON_FILESYSTEM_CLASS_SUBST="$(quoteSubst "${DBCON_FILESYSTEM_CLASS}")"
export DBCON_DATASTORE_CLASS_SUBST="$(quoteSubst "${DBCON_DATASTORE_CLASS}")"
export DBCON_PERSISTENCEMANAGER_CLASS_SUBST="$(quoteSubst "${DBCON_PERSISTENCEMANAGER_CLASS}")"
export DBCON_VALIDATIONQUERY_SUBST="$(quoteSubst "${DBCON_VALIDATIONQUERY}")"

export DBCON_JACKRABBIT_USER_SUBST="$(quoteSubst "${DBCON_JACKRABBIT_USER}")"
export DBCON_JACKRABBIT_PASSWORD_SUBST="$(quoteSubst "${DBCON_JACKRABBIT_PASSWORD}")"
export DBCON_JACKRABBIT_DATABASE_SUBST="$(quoteSubst "${DBCON_JACKRABBIT_DATABASE}")"
export DBCON_JACKRABBIT_URL_SUBST="$(quoteSubst "${DBCON_JACKRABBIT_URL}")"

export DBCON_HIBERNATE_USER_SUBST="$(quoteSubst "${DBCON_HIBERNATE_USER}")"
export DBCON_HIBERNATE_PASSWORD_SUBST="$(quoteSubst "${DBCON_HIBERNATE_PASSWORD}")"
export DBCON_HIBERNATE_DATABASE_SUBST="$(quoteSubst "${DBCON_HIBERNATE_DATABASE}")"
export DBCON_HIBERNATE_URL_SUBST="$(quoteSubst "${DBCON_HIBERNATE_URL}")"
export DBCON_HIBERNATE_CONFIG_FILE_SUBST="$(quoteSubst "${DBCON_HIBERNATE_CONFIG_FILE}")"

export DBCON_QUARTZ_USER_SUBST="$(quoteSubst "${DBCON_QUARTZ_USER}")"
export DBCON_QUARTZ_PASSWORD_SUBST="$(quoteSubst "${DBCON_QUARTZ_PASSWORD}")"
export DBCON_QUARTZ_DATABASE_SUBST="$(quoteSubst "${DBCON_QUARTZ_DATABASE}")"
export DBCON_QUARTZ_URL_SUBST="$(quoteSubst "${DBCON_QUARTZ_URL}")"
