#!/bin/sh

set -eu
export LC_ALL=C

. /usr/local/bin/setup-biserver-set-env

########

# Webapp rename setup
/usr/local/bin/setup-biserver-webapp-rename

# General setup
/usr/local/bin/setup-biserver-general

# PostgreSQL setup
if [ "${BISERVER_STORAGE}" = 'postgres' ]; then
	/usr/local/bin/setup-biserver-postgres
fi

# biserver.init.d setup
/usr/local/bin/setup-biserver-initd
