#!/bin/sh

set -eu
export LC_ALL=C

# Initial setup
if [ ! -f "${HOME}"/.biserver.firstrun.lock ]; then
	touch "${HOME}"/.biserver.firstrun.lock
	/usr/local/bin/setup-biserver
fi

export LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}:${CATALINA_HOME}/lib"
export CATALINA_OPTS="$(cat <<-EOF
	-XX:MaxPermSize=256m
	-Dsun.rmi.dgc.client.gcInterval=3600000
	-Dsun.rmi.dgc.server.gcInterval=3600000
	-Dfile.encoding=utf8
	-DDI_HOME="${DI_HOME}"
	${CATALINA_OPTS_EXTRA-
		-Xms1024m
		-Xmx4096m
	}
EOF
)"

cd "${CATALINA_HOME}"/bin
exec sh catalina.sh run
