#!/bin/sh

set -eu
export LC_ALL=C

. /usr/local/bin/setup-biserver-set-utils

########

if [ ! -f "${HOME}"/.biserver.firstrun.lock ]; then
	touch "${HOME}"/.biserver.firstrun.lock

	if [ -n "${BISERVER_SETUP_JSON}" ]; then
		/usr/local/bin/setup-biserver-multi
	else
		/usr/local/bin/setup-biserver
	fi
fi

########

export LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}:${CATALINA_HOME}/lib"
export CATALINA_OPTS="$(cat <<-EOF
	-XX:MaxPermSize=256m
	-Dsun.rmi.dgc.client.gcInterval=3600000
	-Dsun.rmi.dgc.server.gcInterval=3600000
	-Dfile.encoding=utf8
	-DDI_HOME="${BISERVER_HOME}"/"${BISERVER_KETTLE_DIRNAME}"
	${CATALINA_OPTS_EXTRA-
		-Xms1024m
		-Xmx4096m
	}
EOF
)"

logInfo "Starting Pentaho BI Server..."
cd "${CATALINA_HOME}"/bin
exec sh catalina.sh run
