#!/bin/sh

set -eu
export LC_ALL=C

if [ ! -f "${BISERVER_HOME}"/.biserver.setup.lock ]; then
	# General setup
	/usr/local/bin/setup-general

	# PostgreSQL setup
	if [ "${BISERVER_ENABLE_POSTGRES}" = true ]; then
		/usr/local/bin/setup-postgres
	fi

	# biserver.init.d setup
	/usr/local/bin/setup-initd

	# Create lock file
	touch "${BISERVER_HOME}"/.biserver.setup.lock
fi

export CATALINA_OPTS="$(cat <<-EOF
	-XX:MaxPermSize=256m
	-Dsun.rmi.dgc.client.gcInterval=3600000
	-Dsun.rmi.dgc.server.gcInterval=3600000
	-Dfile.encoding=utf8
	-DDI_HOME="${BISERVER_SOLUTION_PATH}/system/kettle"
	${CATALINA_OPTS_EXTRA-
		-Xms1024m
		-Xmx4096m
	}
EOF
)"

cd "${CATALINA_HOME}"/bin
exec sh catalina.sh run
