#!/bin/sh

set -eu

DI_HOME="${BISERVER_HOME}"/pentaho-solutions/system/kettle
export CATALINA_OPTS="
 -Xms1024m
 -Xmx2048m
 -XX:MaxPermSize=256m
 -Dsun.rmi.dgc.client.gcInterval=3600000
 -Dsun.rmi.dgc.server.gcInterval=3600000
 -Dfile.encoding=utf8 -DDI_HOME=\"${DI_HOME}\"
"

cd "${CATALINA_HOME}"/bin
exec sh catalina.sh run
