#!/bin/sh

set -eu
export LC_ALL=C

if [ ! -f "${BISERVER_HOME}"/.biserver.setup.lock ]; then
	# PostgreSQL setup
	if [ "${BISERVER_ENABLE_POSTGRES}" = true ]; then
		/usr/local/bin/setup-postgres
	fi

	# Initial setup
	/usr/local/bin/setup-init

	# Create lock file
	touch "${BISERVER_HOME}"/.biserver.setup.lock
fi

# Set default CATALINA_OPTS
if [ -z "${CATALINA_OPTS+x}" ]; then
	export CATALINA_OPTS="$(cat <<-EOF
		-Xms2048m
		-Xmx6144m
		-XX:MaxPermSize=256m
		-Dsun.rmi.dgc.client.gcInterval=3600000
		-Dsun.rmi.dgc.server.gcInterval=3600000
		-Dfile.encoding=utf8
		-DDI_HOME="${BISERVER_HOME}/pentaho-solutions/system/kettle"
	EOF
	)"
fi

cd "${CATALINA_HOME}"/bin
exec sh catalina.sh run
