\set POSTGRES_JDBCSEC_USER `printf -- '%s' "${POSTGRES_JDBCSEC_USER:?}"`
\set POSTGRES_JDBCSEC_PASSWORD `printf -- '%s' "${POSTGRES_JDBCSEC_PASSWORD:?}"`
\set POSTGRES_JDBCSEC_DATABASE `printf -- '%s' "${POSTGRES_JDBCSEC_DATABASE:?}"`

CREATE USER :"POSTGRES_JDBCSEC_USER" PASSWORD :'POSTGRES_JDBCSEC_PASSWORD';
CREATE DATABASE :"POSTGRES_JDBCSEC_DATABASE" WITH OWNER = :"POSTGRES_JDBCSEC_USER" ENCODING = 'UTF8' TABLESPACE = pg_default;
GRANT ALL PRIVILEGES ON DATABASE :"POSTGRES_JDBCSEC_DATABASE" TO :"POSTGRES_JDBCSEC_USER";

\connect :"POSTGRES_JDBCSEC_DATABASE" :"POSTGRES_JDBCSEC_USER"

BEGIN;

CREATE TABLE USERS (
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(60) NOT NULL,
	ENABLED BOOLEAN NOT NULL,
	PRIMARY KEY (USERNAME)
);

CREATE TABLE AUTHORITIES (
	AUTHORITY VARCHAR(50) NOT NULL,
	PRIMARY KEY (AUTHORITY)
);

CREATE TABLE GRANTED_AUTHORITIES (
	USERNAME VARCHAR(50) NOT NULL,
	AUTHORITY VARCHAR(50) NOT NULL,
	PRIMARY KEY (USERNAME, AUTHORITY),
	FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
	FOREIGN KEY (AUTHORITY) REFERENCES AUTHORITIES(AUTHORITY)
);

INSERT INTO USERS VALUES('admin', '$2a$10$nbbgKvNWGw9aIBdRvHZhzOo/aUFesk7/mpShJ/aNgj8K7sTMELdi6' /* password */, TRUE);
INSERT INTO USERS VALUES('alice', '$2a$10$nbbgKvNWGw9aIBdRvHZhzOo/aUFesk7/mpShJ/aNgj8K7sTMELdi6' /* password */, TRUE);
INSERT INTO USERS VALUES('bob', '$2a$10$nbbgKvNWGw9aIBdRvHZhzOo/aUFesk7/mpShJ/aNgj8K7sTMELdi6' /* password */, TRUE);
INSERT INTO USERS VALUES('carol', '$2a$10$nbbgKvNWGw9aIBdRvHZhzOo/aUFesk7/mpShJ/aNgj8K7sTMELdi6' /* password */, TRUE);

INSERT INTO AUTHORITIES VALUES('Administrator');
INSERT INTO AUTHORITIES VALUES('Employee');

INSERT INTO GRANTED_AUTHORITIES VALUES('admin', 'Administrator');
INSERT INTO GRANTED_AUTHORITIES VALUES('alice', 'Administrator');
INSERT INTO GRANTED_AUTHORITIES VALUES('bob', 'Employee');
INSERT INTO GRANTED_AUTHORITIES VALUES('carol', 'Employee');

ALTER TABLE USERS OWNER TO :"POSTGRES_JDBCSEC_USER";
ALTER TABLE AUTHORITIES OWNER TO :"POSTGRES_JDBCSEC_USER";
ALTER TABLE GRANTED_AUTHORITIES OWNER TO :"POSTGRES_JDBCSEC_USER";

COMMIT;
