# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: "biserver"

# https://hub.docker.com/_/httpd
x-httpd-image: &httpd-image "docker.io/httpd:2.4"
# https://repo.stratebi.com
x-biserver-image: &biserver-image "repo.stratebi.com/lincebi/biserver:9.5.2.0-272-3"

services:

  httpd:
    image: *httpd-image
    restart: "on-failure:3"
    container_name: "biserver-httpd"
    hostname: "httpd"
    networks:
      - "biserver"
    ports:
      - "8080:8080/tcp"
    volumes:
      - { type: "bind", source: "./config/httpd/httpd.conf", target: "/usr/local/apache2/conf/httpd.conf", read_only: true }
    environment:
      DOMAIN: "${DOMAIN:?}"

  biserver:
    image: *biserver-image
    restart: "on-failure:3"
    container_name: "biserver"
    hostname: "biserver"
    networks:
      - "biserver"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - { type: "bind", source: "./config/biserver/biserver.init.d/", target: "/etc/biserver.init.d/", read_only: true }
      - { type: "volume", source: "biserver-jackrabbit", target: "/var/lib/biserver/pentaho-solutions/system/jackrabbit/repository/" }
      - { type: "volume", source: "biserver-hsqldb", target: "/var/lib/biserver/data/hsqldb/" }
      - { type: "volume", source: "biserver-logs", target: "/var/lib/biserver/tomcat/logs/" }
    environment:
      FQSU_PROTOCOL: "http"
      FQSU_DOMAIN: "${DOMAIN:?}"
      FQSU_PORT: "8080"
      IS_PROXIED: "true"
      LOAD_SAMPLES: "${LOAD_SAMPLES:-true}"
      WEBAPP_PENTAHO_DIRNAME: "${WEBAPP_PENTAHO_DIRNAME:-pentaho}"
      DEFAULT_ADMIN_PASSWORD: "${DEFAULT_ADMIN_PASSWORD:?}"
      STORAGE_TYPE: "local"
      AUDIT_ENTRY: "sql"
      AUDIT_CLEAN_MAX_RETENTION_DAYS: "${AUDIT_CLEAN_MAX_RETENTION_DAYS:-90}"

volumes:

  biserver-jackrabbit:
    name: "biserver-jackrabbit"

  biserver-hsqldb:
    name: "biserver-hsqldb"

  biserver-logs:
    name: "biserver-logs"

networks:

  biserver:
    name: "biserver"
    internal: false
